spring:
  profiles.active: dev
  mvc.view.prefix: /WEB-INF/view/
  mvc.view.suffix: .jsp
server:
  contextPath: /hus
  port: 80


---
spring:
 profiles: dev
 datasource:
     driver: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/hh
     username: root
     password: root
 wechat:
    appID: wxa4cc0a202b65477c
    appsecret: 29d8103ec273d5af766ed8ba7eaec315

